// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/slack-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.SlackSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.SlackSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.SlackSDK, name string) (sdk.SlackEntity, error) {
	switch strings.ToLower(name) {
	case "adminapp":
		return client.Adminapp(nil), nil
	case "adminappsapproved":
		return client.Adminappsapproved(nil), nil
	case "adminappsrequest":
		return client.Adminappsrequest(nil), nil
	case "adminappsrestricted":
		return client.Adminappsrestricted(nil), nil
	case "adminconversation":
		return client.Adminconversation(nil), nil
	case "adminconversationsekm":
		return client.Adminconversationsekm(nil), nil
	case "adminconversationsrestrict_access":
		return client.AdminconversationsrestrictAccess(nil), nil
	case "adminemoji":
		return client.Adminemoji(nil), nil
	case "admininvite_request":
		return client.AdmininviteRequest(nil), nil
	case "admininvite_requestsapproved":
		return client.AdmininviteRequestsapproved(nil), nil
	case "admininvite_requestsdenied":
		return client.AdmininviteRequestsdenied(nil), nil
	case "adminteam":
		return client.Adminteam(nil), nil
	case "adminteamsadmin":
		return client.Adminteamsadmin(nil), nil
	case "adminteamsowner":
		return client.Adminteamsowner(nil), nil
	case "adminteamssetting":
		return client.Adminteamssetting(nil), nil
	case "adminuser":
		return client.Adminuser(nil), nil
	case "adminusergroup":
		return client.Adminusergroup(nil), nil
	case "adminuserssession":
		return client.Adminuserssession(nil), nil
	case "api":
		return client.Api(nil), nil
	case "app":
		return client.App(nil), nil
	case "appseventauthorization":
		return client.Appseventauthorization(nil), nil
	case "appspermission":
		return client.Appspermission(nil), nil
	case "appspermissionsresource":
		return client.Appspermissionsresource(nil), nil
	case "appspermissionsscope":
		return client.Appspermissionsscope(nil), nil
	case "appspermissionsuser":
		return client.Appspermissionsuser(nil), nil
	case "auth":
		return client.Auth(nil), nil
	case "bot":
		return client.Bot(nil), nil
	case "call":
		return client.Call(nil), nil
	case "callsparticipant":
		return client.Callsparticipant(nil), nil
	case "chat":
		return client.Chat(nil), nil
	case "chatscheduled_message":
		return client.ChatscheduledMessage(nil), nil
	case "conversation":
		return client.Conversation(nil), nil
	case "dialog":
		return client.Dialog(nil), nil
	case "dnd":
		return client.Dnd(nil), nil
	case "emoji":
		return client.Emoji(nil), nil
	case "file":
		return client.File(nil), nil
	case "filescomment":
		return client.Filescomment(nil), nil
	case "filesremote":
		return client.Filesremote(nil), nil
	case "migration":
		return client.Migration(nil), nil
	case "oauth":
		return client.Oauth(nil), nil
	case "oauthv2":
		return client.Oauthv2(nil), nil
	case "pin":
		return client.Pin(nil), nil
	case "reaction":
		return client.Reaction(nil), nil
	case "reminder":
		return client.Reminder(nil), nil
	case "rtm":
		return client.Rtm(nil), nil
	case "search":
		return client.Search(nil), nil
	case "star":
		return client.Star(nil), nil
	case "team":
		return client.Team(nil), nil
	case "teamprofile":
		return client.Teamprofile(nil), nil
	case "user":
		return client.User(nil), nil
	case "usergroup":
		return client.Usergroup(nil), nil
	case "usergroupsuser":
		return client.Usergroupsuser(nil), nil
	case "usersprofile":
		return client.Usersprofile(nil), nil
	case "view":
		return client.View(nil), nil
	case "workflow":
		return client.Workflow(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
