<?php
declare(strict_types=1);

// Slack SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SlackUtility::setRegistrar(function (SlackUtility $u): void {
    $u->clean = [SlackClean::class, 'call'];
    $u->done = [SlackDone::class, 'call'];
    $u->make_error = [SlackMakeError::class, 'call'];
    $u->feature_add = [SlackFeatureAdd::class, 'call'];
    $u->feature_hook = [SlackFeatureHook::class, 'call'];
    $u->feature_init = [SlackFeatureInit::class, 'call'];
    $u->fetcher = [SlackFetcher::class, 'call'];
    $u->make_fetch_def = [SlackMakeFetchDef::class, 'call'];
    $u->make_context = [SlackMakeContext::class, 'call'];
    $u->make_options = [SlackMakeOptions::class, 'call'];
    $u->make_request = [SlackMakeRequest::class, 'call'];
    $u->make_response = [SlackMakeResponse::class, 'call'];
    $u->make_result = [SlackMakeResult::class, 'call'];
    $u->make_point = [SlackMakePoint::class, 'call'];
    $u->make_spec = [SlackMakeSpec::class, 'call'];
    $u->make_url = [SlackMakeUrl::class, 'call'];
    $u->param = [SlackParam::class, 'call'];
    $u->prepare_auth = [SlackPrepareAuth::class, 'call'];
    $u->prepare_body = [SlackPrepareBody::class, 'call'];
    $u->prepare_headers = [SlackPrepareHeaders::class, 'call'];
    $u->prepare_method = [SlackPrepareMethod::class, 'call'];
    $u->prepare_params = [SlackPrepareParams::class, 'call'];
    $u->prepare_path = [SlackPreparePath::class, 'call'];
    $u->prepare_query = [SlackPrepareQuery::class, 'call'];
    $u->graphql_body = [SlackGraphql::class, 'body'];
    $u->graphql_errors = [SlackGraphql::class, 'errors'];
    $u->result_basic = [SlackResultBasic::class, 'call'];
    $u->result_body = [SlackResultBody::class, 'call'];
    $u->result_headers = [SlackResultHeaders::class, 'call'];
    $u->transform_request = [SlackTransformRequest::class, 'call'];
    $u->transform_response = [SlackTransformResponse::class, 'call'];
});
